/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPathlessLayoutRouteImport } from './routes/_dashboard/_pathlessLayout'
import { Route as AuthPathlessLayoutRouteImport } from './routes/_auth/_pathlessLayout'
import { Route as DashboardPathlessLayoutPaginaInicialRouteImport } from './routes/_dashboard/_pathlessLayout/pagina-inicial'
import { Route as AuthPathlessLayoutVerificar2faRouteImport } from './routes/_auth/_pathlessLayout/verificar-2fa'
import { Route as AuthPathlessLayoutRedefinirSenhaRouteImport } from './routes/_auth/_pathlessLayout/redefinir-senha'
import { Route as AuthPathlessLayoutRedefinicaoDeSenhaRouteImport } from './routes/_auth/_pathlessLayout/redefinicao-de-senha'
import { Route as AuthPathlessLayoutLoginRouteImport } from './routes/_auth/_pathlessLayout/login'
import { Route as AuthPathlessLayoutHabilitar2faRouteImport } from './routes/_auth/_pathlessLayout/habilitar-2fa'
import { Route as DashboardPathlessLayoutGovernancaAnaliticaIndexRouteImport } from './routes/_dashboard/_pathlessLayout/governanca-analitica/index'
import { Route as DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRouteImport } from './routes/_dashboard/_pathlessLayout/governanca-analitica/formatar-planilha'
import { Route as DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRouteImport } from './routes/_dashboard/_pathlessLayout/governanca-analitica/atualizar-relatorios'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/index'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuarios'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/setores'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/modulos'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/funcoes'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/agencias'
import { Route as DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRouteImport } from './routes/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuario.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPathlessLayoutRoute = DashboardPathlessLayoutRouteImport.update({
  id: '/_dashboard/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathlessLayoutRoute = AuthPathlessLayoutRouteImport.update({
  id: '/_auth/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPathlessLayoutPaginaInicialRoute =
  DashboardPathlessLayoutPaginaInicialRouteImport.update({
    id: '/pagina-inicial',
    path: '/pagina-inicial',
    getParentRoute: () => DashboardPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutVerificar2faRoute =
  AuthPathlessLayoutVerificar2faRouteImport.update({
    id: '/verificar-2fa',
    path: '/verificar-2fa',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutRedefinirSenhaRoute =
  AuthPathlessLayoutRedefinirSenhaRouteImport.update({
    id: '/redefinir-senha',
    path: '/redefinir-senha',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutRedefinicaoDeSenhaRoute =
  AuthPathlessLayoutRedefinicaoDeSenhaRouteImport.update({
    id: '/redefinicao-de-senha',
    path: '/redefinicao-de-senha',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutLoginRoute = AuthPathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthPathlessLayoutRoute,
} as any)
const AuthPathlessLayoutHabilitar2faRoute =
  AuthPathlessLayoutHabilitar2faRouteImport.update({
    id: '/habilitar-2fa',
    path: '/habilitar-2fa',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutGovernancaAnaliticaIndexRoute =
  DashboardPathlessLayoutGovernancaAnaliticaIndexRouteImport.update({
    id: '/governanca-analitica/',
    path: '/governanca-analitica/',
    getParentRoute: () => DashboardPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute =
  DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRouteImport.update({
    id: '/governanca-analitica/formatar-planilha',
    path: '/governanca-analitica/formatar-planilha',
    getParentRoute: () => DashboardPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute =
  DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRouteImport.update(
    {
      id: '/governanca-analitica/atualizar-relatorios',
      path: '/governanca-analitica/atualizar-relatorios',
      getParentRoute: () => DashboardPathlessLayoutRoute,
    } as any,
  )
const DashboardPathlessLayoutAdministracaoPathlessLayoutRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutRouteImport.update({
    id: '/administracao/_pathlessLayout',
    path: '/administracao',
    getParentRoute: () => DashboardPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () =>
      DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRouteImport.update({
    id: '/setores',
    path: '/setores',
    getParentRoute: () =>
      DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () =>
      DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRouteImport.update({
    id: '/funcoes',
    path: '/funcoes',
    getParentRoute: () =>
      DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRouteImport.update({
    id: '/agencias',
    path: '/agencias',
    getParentRoute: () =>
      DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
  } as any)
const DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute =
  DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRouteImport.update(
    {
      id: '/usuario/$userId',
      path: '/usuario/$userId',
      getParentRoute: () =>
        DashboardPathlessLayoutAdministracaoPathlessLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habilitar-2fa': typeof AuthPathlessLayoutHabilitar2faRoute
  '/login': typeof AuthPathlessLayoutLoginRoute
  '/redefinicao-de-senha': typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  '/redefinir-senha': typeof AuthPathlessLayoutRedefinirSenhaRoute
  '/verificar-2fa': typeof AuthPathlessLayoutVerificar2faRoute
  '/pagina-inicial': typeof DashboardPathlessLayoutPaginaInicialRoute
  '/administracao': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRouteWithChildren
  '/governanca-analitica/atualizar-relatorios': typeof DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute
  '/governanca-analitica/formatar-planilha': typeof DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute
  '/governanca-analitica/': typeof DashboardPathlessLayoutGovernancaAnaliticaIndexRoute
  '/administracao/agencias': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute
  '/administracao/funcoes': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute
  '/administracao/modulos': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute
  '/administracao/setores': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute
  '/administracao/usuarios': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute
  '/administracao/': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute
  '/administracao/usuario/$userId': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habilitar-2fa': typeof AuthPathlessLayoutHabilitar2faRoute
  '/login': typeof AuthPathlessLayoutLoginRoute
  '/redefinicao-de-senha': typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  '/redefinir-senha': typeof AuthPathlessLayoutRedefinirSenhaRoute
  '/verificar-2fa': typeof AuthPathlessLayoutVerificar2faRoute
  '/pagina-inicial': typeof DashboardPathlessLayoutPaginaInicialRoute
  '/governanca-analitica/atualizar-relatorios': typeof DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute
  '/governanca-analitica/formatar-planilha': typeof DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute
  '/governanca-analitica': typeof DashboardPathlessLayoutGovernancaAnaliticaIndexRoute
  '/administracao/agencias': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute
  '/administracao/funcoes': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute
  '/administracao/modulos': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute
  '/administracao/setores': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute
  '/administracao/usuarios': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute
  '/administracao': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute
  '/administracao/usuario/$userId': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/_pathlessLayout': typeof AuthPathlessLayoutRouteWithChildren
  '/_dashboard/_pathlessLayout': typeof DashboardPathlessLayoutRouteWithChildren
  '/_auth/_pathlessLayout/habilitar-2fa': typeof AuthPathlessLayoutHabilitar2faRoute
  '/_auth/_pathlessLayout/login': typeof AuthPathlessLayoutLoginRoute
  '/_auth/_pathlessLayout/redefinicao-de-senha': typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  '/_auth/_pathlessLayout/redefinir-senha': typeof AuthPathlessLayoutRedefinirSenhaRoute
  '/_auth/_pathlessLayout/verificar-2fa': typeof AuthPathlessLayoutVerificar2faRoute
  '/_dashboard/_pathlessLayout/pagina-inicial': typeof DashboardPathlessLayoutPaginaInicialRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRouteWithChildren
  '/_dashboard/_pathlessLayout/governanca-analitica/atualizar-relatorios': typeof DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute
  '/_dashboard/_pathlessLayout/governanca-analitica/formatar-planilha': typeof DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute
  '/_dashboard/_pathlessLayout/governanca-analitica/': typeof DashboardPathlessLayoutGovernancaAnaliticaIndexRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/agencias': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/funcoes': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/modulos': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/setores': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuarios': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute
  '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuario/$userId': typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/habilitar-2fa'
    | '/login'
    | '/redefinicao-de-senha'
    | '/redefinir-senha'
    | '/verificar-2fa'
    | '/pagina-inicial'
    | '/administracao'
    | '/governanca-analitica/atualizar-relatorios'
    | '/governanca-analitica/formatar-planilha'
    | '/governanca-analitica/'
    | '/administracao/agencias'
    | '/administracao/funcoes'
    | '/administracao/modulos'
    | '/administracao/setores'
    | '/administracao/usuarios'
    | '/administracao/'
    | '/administracao/usuario/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/habilitar-2fa'
    | '/login'
    | '/redefinicao-de-senha'
    | '/redefinir-senha'
    | '/verificar-2fa'
    | '/pagina-inicial'
    | '/governanca-analitica/atualizar-relatorios'
    | '/governanca-analitica/formatar-planilha'
    | '/governanca-analitica'
    | '/administracao/agencias'
    | '/administracao/funcoes'
    | '/administracao/modulos'
    | '/administracao/setores'
    | '/administracao/usuarios'
    | '/administracao'
    | '/administracao/usuario/$userId'
  id:
    | '__root__'
    | '/'
    | '/_auth/_pathlessLayout'
    | '/_dashboard/_pathlessLayout'
    | '/_auth/_pathlessLayout/habilitar-2fa'
    | '/_auth/_pathlessLayout/login'
    | '/_auth/_pathlessLayout/redefinicao-de-senha'
    | '/_auth/_pathlessLayout/redefinir-senha'
    | '/_auth/_pathlessLayout/verificar-2fa'
    | '/_dashboard/_pathlessLayout/pagina-inicial'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout'
    | '/_dashboard/_pathlessLayout/governanca-analitica/atualizar-relatorios'
    | '/_dashboard/_pathlessLayout/governanca-analitica/formatar-planilha'
    | '/_dashboard/_pathlessLayout/governanca-analitica/'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/agencias'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/funcoes'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/modulos'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/setores'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuarios'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/'
    | '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuario/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathlessLayoutRoute: typeof AuthPathlessLayoutRouteWithChildren
  DashboardPathlessLayoutRoute: typeof DashboardPathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_pathlessLayout': {
      id: '/_dashboard/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_pathlessLayout': {
      id: '/_auth/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_pathlessLayout/pagina-inicial': {
      id: '/_dashboard/_pathlessLayout/pagina-inicial'
      path: '/pagina-inicial'
      fullPath: '/pagina-inicial'
      preLoaderRoute: typeof DashboardPathlessLayoutPaginaInicialRouteImport
      parentRoute: typeof DashboardPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/verificar-2fa': {
      id: '/_auth/_pathlessLayout/verificar-2fa'
      path: '/verificar-2fa'
      fullPath: '/verificar-2fa'
      preLoaderRoute: typeof AuthPathlessLayoutVerificar2faRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/redefinir-senha': {
      id: '/_auth/_pathlessLayout/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof AuthPathlessLayoutRedefinirSenhaRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/redefinicao-de-senha': {
      id: '/_auth/_pathlessLayout/redefinicao-de-senha'
      path: '/redefinicao-de-senha'
      fullPath: '/redefinicao-de-senha'
      preLoaderRoute: typeof AuthPathlessLayoutRedefinicaoDeSenhaRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/login': {
      id: '/_auth/_pathlessLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthPathlessLayoutLoginRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/habilitar-2fa': {
      id: '/_auth/_pathlessLayout/habilitar-2fa'
      path: '/habilitar-2fa'
      fullPath: '/habilitar-2fa'
      preLoaderRoute: typeof AuthPathlessLayoutHabilitar2faRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/governanca-analitica/': {
      id: '/_dashboard/_pathlessLayout/governanca-analitica/'
      path: '/governanca-analitica'
      fullPath: '/governanca-analitica/'
      preLoaderRoute: typeof DashboardPathlessLayoutGovernancaAnaliticaIndexRouteImport
      parentRoute: typeof DashboardPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/governanca-analitica/formatar-planilha': {
      id: '/_dashboard/_pathlessLayout/governanca-analitica/formatar-planilha'
      path: '/governanca-analitica/formatar-planilha'
      fullPath: '/governanca-analitica/formatar-planilha'
      preLoaderRoute: typeof DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRouteImport
      parentRoute: typeof DashboardPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/governanca-analitica/atualizar-relatorios': {
      id: '/_dashboard/_pathlessLayout/governanca-analitica/atualizar-relatorios'
      path: '/governanca-analitica/atualizar-relatorios'
      fullPath: '/governanca-analitica/atualizar-relatorios'
      preLoaderRoute: typeof DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRouteImport
      parentRoute: typeof DashboardPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRouteImport
      parentRoute: typeof DashboardPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/'
      path: '/'
      fullPath: '/administracao/'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuarios': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuarios'
      path: '/usuarios'
      fullPath: '/administracao/usuarios'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/setores': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/setores'
      path: '/setores'
      fullPath: '/administracao/setores'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/modulos': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/modulos'
      path: '/modulos'
      fullPath: '/administracao/modulos'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/funcoes': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/funcoes'
      path: '/funcoes'
      fullPath: '/administracao/funcoes'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/agencias': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/agencias'
      path: '/agencias'
      fullPath: '/administracao/agencias'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
    '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuario/$userId': {
      id: '/_dashboard/_pathlessLayout/administracao/_pathlessLayout/usuario/$userId'
      path: '/usuario/$userId'
      fullPath: '/administracao/usuario/$userId'
      preLoaderRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRouteImport
      parentRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRoute
    }
  }
}

interface AuthPathlessLayoutRouteChildren {
  AuthPathlessLayoutHabilitar2faRoute: typeof AuthPathlessLayoutHabilitar2faRoute
  AuthPathlessLayoutLoginRoute: typeof AuthPathlessLayoutLoginRoute
  AuthPathlessLayoutRedefinicaoDeSenhaRoute: typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  AuthPathlessLayoutRedefinirSenhaRoute: typeof AuthPathlessLayoutRedefinirSenhaRoute
  AuthPathlessLayoutVerificar2faRoute: typeof AuthPathlessLayoutVerificar2faRoute
}

const AuthPathlessLayoutRouteChildren: AuthPathlessLayoutRouteChildren = {
  AuthPathlessLayoutHabilitar2faRoute: AuthPathlessLayoutHabilitar2faRoute,
  AuthPathlessLayoutLoginRoute: AuthPathlessLayoutLoginRoute,
  AuthPathlessLayoutRedefinicaoDeSenhaRoute:
    AuthPathlessLayoutRedefinicaoDeSenhaRoute,
  AuthPathlessLayoutRedefinirSenhaRoute: AuthPathlessLayoutRedefinirSenhaRoute,
  AuthPathlessLayoutVerificar2faRoute: AuthPathlessLayoutVerificar2faRoute,
}

const AuthPathlessLayoutRouteWithChildren =
  AuthPathlessLayoutRoute._addFileChildren(AuthPathlessLayoutRouteChildren)

interface DashboardPathlessLayoutAdministracaoPathlessLayoutRouteChildren {
  DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute
}

const DashboardPathlessLayoutAdministracaoPathlessLayoutRouteChildren: DashboardPathlessLayoutAdministracaoPathlessLayoutRouteChildren =
  {
    DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutAgenciasRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutFuncoesRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutModulosRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutSetoresRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutUsuariosRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutIndexRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutUsuarioUserIdRoute,
  }

const DashboardPathlessLayoutAdministracaoPathlessLayoutRouteWithChildren =
  DashboardPathlessLayoutAdministracaoPathlessLayoutRoute._addFileChildren(
    DashboardPathlessLayoutAdministracaoPathlessLayoutRouteChildren,
  )

interface DashboardPathlessLayoutRouteChildren {
  DashboardPathlessLayoutPaginaInicialRoute: typeof DashboardPathlessLayoutPaginaInicialRoute
  DashboardPathlessLayoutAdministracaoPathlessLayoutRoute: typeof DashboardPathlessLayoutAdministracaoPathlessLayoutRouteWithChildren
  DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute: typeof DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute
  DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute: typeof DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute
  DashboardPathlessLayoutGovernancaAnaliticaIndexRoute: typeof DashboardPathlessLayoutGovernancaAnaliticaIndexRoute
}

const DashboardPathlessLayoutRouteChildren: DashboardPathlessLayoutRouteChildren =
  {
    DashboardPathlessLayoutPaginaInicialRoute:
      DashboardPathlessLayoutPaginaInicialRoute,
    DashboardPathlessLayoutAdministracaoPathlessLayoutRoute:
      DashboardPathlessLayoutAdministracaoPathlessLayoutRouteWithChildren,
    DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute:
      DashboardPathlessLayoutGovernancaAnaliticaAtualizarRelatoriosRoute,
    DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute:
      DashboardPathlessLayoutGovernancaAnaliticaFormatarPlanilhaRoute,
    DashboardPathlessLayoutGovernancaAnaliticaIndexRoute:
      DashboardPathlessLayoutGovernancaAnaliticaIndexRoute,
  }

const DashboardPathlessLayoutRouteWithChildren =
  DashboardPathlessLayoutRoute._addFileChildren(
    DashboardPathlessLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathlessLayoutRoute: AuthPathlessLayoutRouteWithChildren,
  DashboardPathlessLayoutRoute: DashboardPathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
