/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPathlessLayoutRouteImport } from './routes/_dashboard/_pathlessLayout'
import { Route as AuthPathlessLayoutRouteImport } from './routes/_auth/_pathlessLayout'
import { Route as DashboardPathlessLayoutPaginaInicialRouteImport } from './routes/_dashboard/_pathlessLayout/pagina-inicial'
import { Route as AuthPathlessLayoutVerificacao2faRouteImport } from './routes/_auth/_pathlessLayout/verificacao-2fa'
import { Route as AuthPathlessLayoutRedefinirSenhaRouteImport } from './routes/_auth/_pathlessLayout/redefinir-senha'
import { Route as AuthPathlessLayoutRedefinicaoDeSenhaRouteImport } from './routes/_auth/_pathlessLayout/redefinicao-de-senha'
import { Route as AuthPathlessLayoutLoginRouteImport } from './routes/_auth/_pathlessLayout/login'
import { Route as AuthPathlessLayoutHabilitar2faRouteImport } from './routes/_auth/_pathlessLayout/habilitar-2fa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPathlessLayoutRoute = DashboardPathlessLayoutRouteImport.update({
  id: '/_dashboard/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathlessLayoutRoute = AuthPathlessLayoutRouteImport.update({
  id: '/_auth/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPathlessLayoutPaginaInicialRoute =
  DashboardPathlessLayoutPaginaInicialRouteImport.update({
    id: '/pagina-inicial',
    path: '/pagina-inicial',
    getParentRoute: () => DashboardPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutVerificacao2faRoute =
  AuthPathlessLayoutVerificacao2faRouteImport.update({
    id: '/verificacao-2fa',
    path: '/verificacao-2fa',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutRedefinirSenhaRoute =
  AuthPathlessLayoutRedefinirSenhaRouteImport.update({
    id: '/redefinir-senha',
    path: '/redefinir-senha',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutRedefinicaoDeSenhaRoute =
  AuthPathlessLayoutRedefinicaoDeSenhaRouteImport.update({
    id: '/redefinicao-de-senha',
    path: '/redefinicao-de-senha',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)
const AuthPathlessLayoutLoginRoute = AuthPathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthPathlessLayoutRoute,
} as any)
const AuthPathlessLayoutHabilitar2faRoute =
  AuthPathlessLayoutHabilitar2faRouteImport.update({
    id: '/habilitar-2fa',
    path: '/habilitar-2fa',
    getParentRoute: () => AuthPathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habilitar-2fa': typeof AuthPathlessLayoutHabilitar2faRoute
  '/login': typeof AuthPathlessLayoutLoginRoute
  '/redefinicao-de-senha': typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  '/redefinir-senha': typeof AuthPathlessLayoutRedefinirSenhaRoute
  '/verificacao-2fa': typeof AuthPathlessLayoutVerificacao2faRoute
  '/pagina-inicial': typeof DashboardPathlessLayoutPaginaInicialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habilitar-2fa': typeof AuthPathlessLayoutHabilitar2faRoute
  '/login': typeof AuthPathlessLayoutLoginRoute
  '/redefinicao-de-senha': typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  '/redefinir-senha': typeof AuthPathlessLayoutRedefinirSenhaRoute
  '/verificacao-2fa': typeof AuthPathlessLayoutVerificacao2faRoute
  '/pagina-inicial': typeof DashboardPathlessLayoutPaginaInicialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/_pathlessLayout': typeof AuthPathlessLayoutRouteWithChildren
  '/_dashboard/_pathlessLayout': typeof DashboardPathlessLayoutRouteWithChildren
  '/_auth/_pathlessLayout/habilitar-2fa': typeof AuthPathlessLayoutHabilitar2faRoute
  '/_auth/_pathlessLayout/login': typeof AuthPathlessLayoutLoginRoute
  '/_auth/_pathlessLayout/redefinicao-de-senha': typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  '/_auth/_pathlessLayout/redefinir-senha': typeof AuthPathlessLayoutRedefinirSenhaRoute
  '/_auth/_pathlessLayout/verificacao-2fa': typeof AuthPathlessLayoutVerificacao2faRoute
  '/_dashboard/_pathlessLayout/pagina-inicial': typeof DashboardPathlessLayoutPaginaInicialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/habilitar-2fa'
    | '/login'
    | '/redefinicao-de-senha'
    | '/redefinir-senha'
    | '/verificacao-2fa'
    | '/pagina-inicial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/habilitar-2fa'
    | '/login'
    | '/redefinicao-de-senha'
    | '/redefinir-senha'
    | '/verificacao-2fa'
    | '/pagina-inicial'
  id:
    | '__root__'
    | '/'
    | '/_auth/_pathlessLayout'
    | '/_dashboard/_pathlessLayout'
    | '/_auth/_pathlessLayout/habilitar-2fa'
    | '/_auth/_pathlessLayout/login'
    | '/_auth/_pathlessLayout/redefinicao-de-senha'
    | '/_auth/_pathlessLayout/redefinir-senha'
    | '/_auth/_pathlessLayout/verificacao-2fa'
    | '/_dashboard/_pathlessLayout/pagina-inicial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathlessLayoutRoute: typeof AuthPathlessLayoutRouteWithChildren
  DashboardPathlessLayoutRoute: typeof DashboardPathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_pathlessLayout': {
      id: '/_dashboard/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_pathlessLayout': {
      id: '/_auth/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_pathlessLayout/pagina-inicial': {
      id: '/_dashboard/_pathlessLayout/pagina-inicial'
      path: '/pagina-inicial'
      fullPath: '/pagina-inicial'
      preLoaderRoute: typeof DashboardPathlessLayoutPaginaInicialRouteImport
      parentRoute: typeof DashboardPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/verificacao-2fa': {
      id: '/_auth/_pathlessLayout/verificacao-2fa'
      path: '/verificacao-2fa'
      fullPath: '/verificacao-2fa'
      preLoaderRoute: typeof AuthPathlessLayoutVerificacao2faRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/redefinir-senha': {
      id: '/_auth/_pathlessLayout/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof AuthPathlessLayoutRedefinirSenhaRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/redefinicao-de-senha': {
      id: '/_auth/_pathlessLayout/redefinicao-de-senha'
      path: '/redefinicao-de-senha'
      fullPath: '/redefinicao-de-senha'
      preLoaderRoute: typeof AuthPathlessLayoutRedefinicaoDeSenhaRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/login': {
      id: '/_auth/_pathlessLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthPathlessLayoutLoginRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/habilitar-2fa': {
      id: '/_auth/_pathlessLayout/habilitar-2fa'
      path: '/habilitar-2fa'
      fullPath: '/habilitar-2fa'
      preLoaderRoute: typeof AuthPathlessLayoutHabilitar2faRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
  }
}

interface AuthPathlessLayoutRouteChildren {
  AuthPathlessLayoutHabilitar2faRoute: typeof AuthPathlessLayoutHabilitar2faRoute
  AuthPathlessLayoutLoginRoute: typeof AuthPathlessLayoutLoginRoute
  AuthPathlessLayoutRedefinicaoDeSenhaRoute: typeof AuthPathlessLayoutRedefinicaoDeSenhaRoute
  AuthPathlessLayoutRedefinirSenhaRoute: typeof AuthPathlessLayoutRedefinirSenhaRoute
  AuthPathlessLayoutVerificacao2faRoute: typeof AuthPathlessLayoutVerificacao2faRoute
}

const AuthPathlessLayoutRouteChildren: AuthPathlessLayoutRouteChildren = {
  AuthPathlessLayoutHabilitar2faRoute: AuthPathlessLayoutHabilitar2faRoute,
  AuthPathlessLayoutLoginRoute: AuthPathlessLayoutLoginRoute,
  AuthPathlessLayoutRedefinicaoDeSenhaRoute:
    AuthPathlessLayoutRedefinicaoDeSenhaRoute,
  AuthPathlessLayoutRedefinirSenhaRoute: AuthPathlessLayoutRedefinirSenhaRoute,
  AuthPathlessLayoutVerificacao2faRoute: AuthPathlessLayoutVerificacao2faRoute,
}

const AuthPathlessLayoutRouteWithChildren =
  AuthPathlessLayoutRoute._addFileChildren(AuthPathlessLayoutRouteChildren)

interface DashboardPathlessLayoutRouteChildren {
  DashboardPathlessLayoutPaginaInicialRoute: typeof DashboardPathlessLayoutPaginaInicialRoute
}

const DashboardPathlessLayoutRouteChildren: DashboardPathlessLayoutRouteChildren =
  {
    DashboardPathlessLayoutPaginaInicialRoute:
      DashboardPathlessLayoutPaginaInicialRoute,
  }

const DashboardPathlessLayoutRouteWithChildren =
  DashboardPathlessLayoutRoute._addFileChildren(
    DashboardPathlessLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathlessLayoutRoute: AuthPathlessLayoutRouteWithChildren,
  DashboardPathlessLayoutRoute: DashboardPathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
